"""add_is_approved_column

Revision ID: e0426ad9d5e2
Revises: f358c6fa25e7
Create Date: 2026-01-03 15:57:54.066311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0426ad9d5e2'
down_revision: Union[str, Sequence[str], None] = 'f358c6fa25e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default first (for existing rows)
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_users_is_approved'), 'users', ['is_approved'], unique=False)
    # Remove the server default after column is created (model uses default=True)
    op.alter_column('users', 'is_approved', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_approved'), table_name='users')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
